# Try to find Soprano
# SOPRANO_FOUND
# SOPRANO_INCLUDE_DIRS
# SOPRANO_LIBRARIES
# SOPRANO_DEFINITIONS

find_package(PkgConfig)
pkg_check_modules(_SOPRANO QUIET soprano)
set(SOPRANO_DEFINITIONS ${_SOPRANO_CFLAGS_OTHER})

find_path(SOPRANO_INCLUDE_DIR Soprano
    HINTS ${_SOPRANO_INCLUDEDIR} ${_SOPRANO_INCLUDE_DIRS})

find_library(SOPRANO_LIBRARY NAMES soprano
    HINTS ${_SOPRANO_LIBDIR} ${_SOPRANO_LIBRARY_DIRS})

set(SOPRANO_INCLUDE_DIRS ${SOPRANO_INCLUDE_DIR})
set(SOPRANO_LIBRARIES ${SOPRANO_LIBRARY})

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(Soprano DEFAULT_MSG
    SOPRANO_LIBRARY SOPRANO_INCLUDE_DIR)

mark_as_advanced(SOPRANO_INCLUDE_DIR SOPRANO_LIBRARY)

