/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbus.xml -a dbus -p dbus_proxy
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WNTRLING_ADAPTORS_HPP
#define WNTRLING_ADAPTORS_HPP

#include "systemadaptor.hpp"

#endif
// kate: indent-mode cstyle; indent-width 4; replace-tabs on; 
