/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbus.xml -a dbus -p dbus_proxy
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef _WNTRLING_INTERFACES_HPP_
#define _WNTRLING_INTERFACES_HPP_

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

namespace Wintermute
{
namespace Linguistics
{
/*
 * Proxy class for interface org.thesii.Wintermute.Linguistics.System
 */
class SystemInterface: public QDBusAbstractInterface
{
    Q_OBJECT

public:
    static inline const char* staticInterfaceName() {
        return "org.thesii.Wintermute.Linguistics.System";
    }

public:
    SystemInterface();
    ~SystemInterface();

public slots:
    Q_NOREPLY void start();
    Q_NOREPLY void stop();
    QDBusPendingReply<> tellSystem (const QString&);

signals:
    void responseFormed (const QString&);
    void started();
    void stopped();
};
}
}
#endif
// kate: indent-mode cstyle; indent-width 4; replace-tabs on; 
