# Find zmq.hpp

INCLUDE(FindPkgConfig)

PKG_SEARCH_MODULE(ZMQ REQUIRED
  libzmq>=2.2 libzmq<=4.2)

set(ZEROMQCXX_LIBRARIES ${ZMQ_LIBRARIES})
set(ZEROMQCXX_INCLUDE_DIR ${ZMQ_INCLUDE_DIRS})
set(ZEROMQCXX_CFLAGS ${ZMQ_CFLAGS} ${ZMQ_CFLAGS_OTHER})
set(ZEROMQCXX_LDFLAGS ${ZMQ_LDFLAGS} ${ZMQ_LDFLAGS_OTHER})
set(ZEROMQCXX_FOUND ZMQ_FOUND)
