include(WinterDefaults)

set(WINTER_BIN_INSTALL_DIR "${WINTER_INSTALL_DIR}/bin")
set(WINTER_LIB_INSTALL_DIR "${WINTER_INSTALL_DIR}/lib")
set(WINTER_PLUGIN_INSTALL_DIR "${WINTER_LIB_INSTALL_DIR}/wntr")
set(WINTER_INCLUDE_INSTALL_DIR "${WINTER_INSTALL_DIR}/include")
set(WINTER_DATA_INSTALL_DIR "${WINTER_INSTALL_DIR}/share/wintermute")
set(WINTER_PLUGINSPEC_INSTALL_DIR "${WINTER_DATA_INSTALL_DIR}/plugins")

## Our CMake default Module-dir
set(CMAKE_MODULE_DIR "${WINTER_INSTALL_DIR}/share/cmake-2.8/Modules")
