## Useful options and variables
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_INCLUDE_DIRECTORIES_PROJECT_BEFORE ON)

set(GENERIC_LIB_VERSION 0.0.1)
set(GENERIC_LIB_SOVERSION 0)

set(WINTER_INSTALL_DIR /usr)
set(WINTER_NON_GENERIC_LIB_VERSION )
set(WINTER_NON_GENERIC_LIB_SOVERSION )

set(WINTER_DEFAULT_LOCALE "en" CACHE STRING "The standard locale to use in Wintermute.")
